### ISSUE TITLE
Not showing on desktop app.

### ISSUE THREAD

**Issue by borisrorsvort** [jackiecorn/figma-files-list-view#1]
osx 10.14.4.
figma v. Figma Desktop App release 71 build 4
<img width="434" alt="Recent Files 2019-05-07 09-03-33" src="https://user-images.githubusercontent.com/39081/57278553-0f4c0380-70a7-11e9-9a96-ce36f17b9a85.png">

**Comment by jackiecorn** [comment]
Have you tried restarting the Figma app?

**Comment by borisrorsvort** [comment]
Yes

**Comment by jackiecorn** [comment]
Does it show up when you switch between Recent, Drafts and Delete?

Can you go to Help -> Toggle Developer Tools -> Console and take a screenshot of any errors?

**Comment by borisrorsvort** [comment]
Yes! But no errors in the console

**Comment by jackiecorn** [comment]
I see. So it only doesn't show up when you first launch into the Recent page?

**Comment by borisrorsvort** [comment]
Nope indeed

**Comment by jackiecorn** [comment]
Ok thanks, I'll look into the problem soon.

**Comment by jackiecorn** [comment]
I have just pushed an update to the plugin, can you try again and let me know if it works?

**Comment by borisrorsvort** [comment]
yep that works now 👌  thanks 🎉
